name: RTSMinecraft
version: 1.0.0
main: dev.mryd.Main
depend: [ProtocolLib, Citizens]
authors:
  - Marayd
  - Zorsh
api-version: '1.21'
commands:
  rts:
    description: RTS Admin command
    permission: op